### PR TITLE
Fix default shell script in BatchSystem & split SLURM 

### PR DESCRIPTION
**Pull request by IzaakWN**
@pmastrap, can you review & sign off, please?

### CODE REVIEW

**Comment by pmastrap** [comment]
@IzaakWN I am testing it by running e.g. `pico.py submit -y 2022_preEE -c etau  -_test -s DY` but it looks like it's submitting just one job and producing only like `pico_etau_test_0.root`. No clue what could be the problem

**Comment by IzaakWN** [comment]
Thanks for testing the PR! Weird that now it only submits one job...
1. Just to be sure: Did you change your batch system in `config.json` to `SLURM_UCL`? `pico.py set batch SLURM_UCL `?
2. If so, can you please see if this happens because `pico.py` only prepares one job,
3. or if it does prepare as many jobs as expected, does it happen because of some wrong configuration of the SLURM (i.e. in the full `sbatch` command or something with the shell `submit_SLURM_UCL.sh` script)?

**Comment by pmastrap** [comment]
Issue is solved changing this if-statement https://github.com/IzaakWN/TauFW/blob/PODAS23/PicoProducer/python/pico/job.py#L800-L802
in `elif 'SLURM' in batch.system`. Thanks!

**Comment by IzaakWN** [comment]
Fixed with https://github.com/cardinia/TauFW/pull/12/commits/c2dc3d9e24c856233105f54f35b472b499ef06a4. Thanks a lot for catching this!

As discussed privately, it's probably bad practice to put a bunch of if statements handling the particular batch options because of reasons we just found out... It might be better to absorb these into the different `BatchSystem` classes and let some class method handle it.

@cardinia, feel free to merge.

**Pull request merged**
